// ═══════════════════════════════════════════════════
// PORTFOLIO CONSTANTS & DATA
// ═══════════════════════════════════════════════════

export const NAV_ITEMS = [
  { id: 'hero', label: 'Home', icon: '◆' },
  { id: 'about', label: 'About', icon: '◈' },
  { id: 'skills', label: 'Skills', icon: '⬡' },
  { id: 'projects', label: 'Projects', icon: '⬢' },
  { id: 'timeline', label: 'Journey', icon: '◉' },
  { id: 'achievements', label: 'Awards', icon: '★' },
  { id: 'contact', label: 'Contact', icon: '◈' },
] as const;

export const LOADER_STEPS = [
  'Initializing Portfolio...',
  'Scanning Engineering Database...',
  'Loading RTL Modules...',
  'Compiling Logic...',
  'Connecting FPGA...',
  'Calibrating Embedded Systems...',
  'Launching AI Core...',
  'System Ready',
] as const;

export const SKILL_CATEGORIES = [
  {
    title: 'RTL Design',
    icon: '⬡',
    color: '#E10600',
    skills: [
      { name: 'Verilog', level: 92 },
      { name: 'SystemVerilog', level: 88 },
      { name: 'UVM', level: 80 },
      { name: 'FPGA', level: 90 },
      { name: 'Vivado', level: 88 },
      { name: 'ModelSim', level: 85 },
    ],
  },
  {
    title: 'Embedded Systems',
    icon: '⚙',
    color: '#E10600',
    skills: [
      { name: 'ESP32', level: 90 },
      { name: 'Arduino', level: 92 },
      { name: 'STM32', level: 78 },
      { name: 'PCB Design', level: 82 },
      { name: 'Linux', level: 80 },
      { name: 'Git', level: 85 },
    ],
  },
  {
    title: 'Protocols',
    icon: '◎',
    color: '#A60000',
    skills: [
      { name: 'UART', level: 90 },
      { name: 'SPI', level: 88 },
      { name: 'I2C', level: 88 },
      { name: 'AHB', level: 85 },
      { name: 'APB', level: 85 },
      { name: 'AXI', level: 80 },
    ],
  },
  {
    title: 'Programming',
    icon: '▦',
    color: '#FF2B2B',
    skills: [
      { name: 'Python', level: 88 },
      { name: 'C', level: 90 },
      { name: 'HTML/CSS', level: 85 },
      { name: 'JavaScript', level: 82 },
      { name: 'React', level: 78 },
      { name: 'TypeScript', level: 75 },
    ],
  },
] as const;

export const PROJECTS = [
  {
    id: 'ahb-apb-bridge',
    title: 'AHB to APB Bridge',
    subtitle: 'AMBA Protocol Bridge Design',
    category: 'RTL Design',
    description: 'Designed and verified an AHB to APB bridge facilitating communication between high-performance AHB masters and low-bandwidth APB peripherals. Implements full AMBA protocol compliance with burst transfer support.',
    problem: 'High-performance processors need to communicate with low-speed peripherals efficiently without stalling the main bus.',
    objectives: ['AMBA AHB-Lite compliant design', 'Burst transfer handling', 'Error response propagation', 'Low-latency bridge operation'],
    techStack: ['Verilog', 'SystemVerilog', 'UVM', 'ModelSim', 'Vivado'],
    architecture: 'Implements a master FSM that sequences AHB phases (address, data) into corresponding APB transfers (setup, access). Includes address decoder, data steering logic, and wait-state generation.',
    highlights: ['Full AHB-Lite protocol support', 'Configurable address map', 'Zero wait-state APB access', 'UVM-based verification'],
    color: '#E10600',
  },
  {
    id: 'router-1x3',
    title: 'Router 1×3',
    subtitle: 'Packet Router Design',
    category: 'RTL Design',
    description: 'A high-performance 1-to-3 packet router that directs incoming data packets to one of three output ports based on the destination address field in the packet header.',
    problem: 'Network-on-chip architectures require efficient packet routing with minimal latency and zero packet loss.',
    objectives: ['Header-based routing', 'FIFO buffering per output port', 'Backpressure handling', 'Error detection'],
    techStack: ['Verilog', 'ModelSim', 'Vivado'],
    architecture: 'Three-stage pipeline: header decode, route computation, and output arbitration. Each output port has a dedicated FIFO buffer for flow control.',
    highlights: ['3-stage pipeline architecture', 'Per-port FIFO buffers', 'Configurable routing table', 'Full simulation coverage'],
    color: '#A60000',
  },

  {
    id: 'mac-unit',
    title: 'MAC Unit',
    subtitle: 'Multiply-Accumulate Engine',
    category: 'RTL Design',
    description: 'A pipelined Multiply-Accumulate (MAC) unit optimized for DSP and AI inference workloads. Supports fixed-point arithmetic with configurable bit-widths.',
    problem: 'AI and DSP applications demand high-throughput MAC operations with minimal latency.',
    objectives: ['Pipelined MAC operation', 'Fixed-point support', 'Overflow detection', 'High clock frequency'],
    techStack: ['Verilog', 'SystemVerilog', 'Vivado'],
    architecture: 'Two-stage pipeline with dedicated multiplier in stage 1 and accumulator with saturation logic in stage 2.',
    highlights: ['500MHz operation', '16/32-bit configurable', 'Saturation arithmetic', 'AI inference ready'],
    color: '#E10600',
  },
  {
    id: 'companion-robot',
    title: 'Companion Robot',
    subtitle: 'AI-Powered Interactive Robot',
    category: 'Robotics',
    description: 'An intelligent companion robot featuring voice interaction, gesture recognition, obstacle avoidance, and emotional expression through LED matrix displays.',
    problem: 'Building an accessible, interactive robot that can engage with users through multiple modalities.',
    objectives: ['Voice command processing', 'Autonomous navigation', 'Emotion display system', 'Gesture recognition'],
    techStack: ['ESP32', 'Arduino', 'Python', 'TensorFlow Lite', 'PCB Design'],
    architecture: 'Dual-core ESP32 architecture: Core 0 handles sensor fusion and motor control, Core 1 manages AI inference and communication.',
    highlights: ['Real-time voice processing', '360° obstacle avoidance', 'Emotion LED matrix', 'BLE connectivity'],
    color: '#FF2B2B',
  },
  {
    id: 'spider-robot',
    title: 'Spider Robot',
    subtitle: 'Multi-Legged Locomotion Platform',
    category: 'Robotics',
    description: 'A hexapod spider robot with 18 degrees of freedom, implementing inverse kinematics for smooth multi-gait locomotion across varied terrain.',
    problem: 'Wheeled robots fail on uneven terrain. Legged locomotion offers superior adaptability.',
    objectives: ['Hexapod gait algorithms', 'Inverse kinematics', 'Terrain adaptation', 'Remote control'],
    techStack: ['Arduino', 'Servo Motors', 'Python', '3D Printing', 'PCB Design'],
    architecture: '6-leg hexapod with 3 DOF per leg. Central controller computes IK solutions and generates coordinated gait patterns.',
    highlights: ['6 gait patterns', '18-DOF articulation', 'Real-time IK solver', 'Terrain-adaptive walking'],
    color: '#E10600',
  },
  {
    id: 'voice-assistant',
    title: 'ESP32 AI Voice Assistant',
    subtitle: 'Edge AI Voice Processing',
    category: 'Embedded',
    description: 'A standalone voice assistant running on ESP32 with wake word detection, speech recognition, and natural language processing at the edge.',
    problem: 'Cloud-dependent voice assistants have latency and privacy concerns. Edge processing solves both.',
    objectives: ['Wake word detection', 'On-device speech recognition', 'IoT device control', 'Low power consumption'],
    techStack: ['ESP32', 'TensorFlow Lite', 'C++', 'Python', 'MQTT'],
    architecture: 'Audio pipeline: I2S microphone → FFT → MFCC features → TFLite model → Command parser → MQTT action dispatch.',
    highlights: ['< 200ms response time', 'On-device inference', 'IoT integration', 'Custom wake word'],
    color: '#A60000',
  },
] as const;

export const TIMELINE_EVENTS = [
  {
    year: 'Feb 2026 – Present',
    title: 'RTL Design & Verification Engineer',
    subtitle: 'Kiwistron Pvt Ltd',
    description: 'Working on next-generation RTL design and verification, SystemVerilog/UVM workflows, Embedded Systems, and AIoT solutions into production-ready products.',
    type: 'work' as const,
    icon: '◆',
  },
  {
    year: '2025',
    title: 'Bachelor of Engineering Completed',
    subtitle: 'K. Ramakrishnan College of Engineering',
    description: 'Graduated with 7.92 CGPA. Completed multiple RTL design, FPGA, embedded systems projects while serving as Class Representative.',
    type: 'education' as const,
    icon: '★',
  },
  {
    year: '2025',
    title: 'Advanced VLSI Design & Verification Program',
    subtitle: 'Maven Silicon',
    description: 'Covered RTL Design, SystemVerilog, Functional Verification, AMBA Protocols (AHB/APB), FSM Design, and FPGA Design Flow.',
    type: 'certification' as const,
    icon: '⬡',
  },
  {
    year: '2024',
    title: 'Maven Silicon – VLSI Internship',
    subtitle: 'Industrial Training',
    description: 'Practical exposure to industry-standard RTL design and verification workflows, Verilog HDL, SystemVerilog, and Timing Analysis.',
    type: 'internship' as const,
    icon: '◈',
  },
  {
    year: '2023',
    title: 'PMKVY – VLSI Design Certification',
    subtitle: 'Electronics Sector Skill Council',
    description: 'Key learnings in Digital Electronics, CMOS Fundamentals, RTL Design, Simulation, and Digital Design Verification.',
    type: 'certification' as const,
    icon: '⬡',
  },
  {
    year: '2023',
    title: 'Embedded Systems Internship',
    subtitle: 'Industrial Training',
    description: 'Worked on Microcontroller Programming, Sensor Integration, Communication Protocols (UART, SPI, I²C), and IoT Applications.',
    type: 'internship' as const,
    icon: '◈',
  },
  {
    year: '2022',
    title: 'Embedded Systems & IoT Workshop',
    subtitle: 'Workshop',
    description: 'Gained practical experience with Arduino, ESP32, sensors, and IoT system design, strengthening hardware-software integration skills.',
    type: 'certification' as const,
    icon: '⬡',
  },
  {
    year: '2021',
    title: 'B.E. Electronics & Communication',
    subtitle: 'K. Ramakrishnan College of Engineering',
    description: 'Began engineering journey focusing on Digital Electronics, Embedded Systems, FPGA, and VLSI fundamentals.',
    type: 'education' as const,
    icon: '★',
  },
  {
    year: '2021',
    title: 'Higher Secondary (HSC)',
    subtitle: 'Eden Gardens Matric Higher Secondary School',
    description: 'Completed with 74.7% in the Science stream, strengthening analytical and problem-solving skills.',
    type: 'education' as const,
    icon: '★',
  },
  {
    year: '2019',
    title: 'Secondary School (SSLC)',
    subtitle: 'Annai Paruvathamma Matriculation School',
    description: 'Completed with 66.6%, building a strong foundation in Mathematics, Science, and Electronics.',
    type: 'education' as const,
    icon: '★',
  },
] as const;

export const ACHIEVEMENTS = [
  {
    title: 'Leadership Excellence',
    description: 'Served as Class Representative for all four years (2021–2025), bridging students and faculty, coordinating academic activities and resolving concerns.',
    icon: '🏆',
    color: '#E10600',
  },
  {
    title: 'Technical Event Coordinator',
    description: 'Successfully organized department-level technical symposiums, engineering events, and idea presentation sessions, encouraging innovation and teamwork.',
    icon: '🎤',
    color: '#E10600',
  },
  {
    title: 'VLSI Design Certification',
    description: 'Completed PMKVY – VLSI Engineer Certification with practical knowledge in RTL Design, Verilog HDL, Digital Logic Design, and Verification.',
    icon: '💡',
    color: '#E10600',
  },
  {
    title: 'Advanced VLSI Design & Verification',
    description: 'Completed the Advanced VLSI Design & Verification Program at Maven Silicon, covering RTL Design, SystemVerilog, Functional Verification, and AMBA protocols.',
    icon: '🚀',
    color: '#E10600',
  },
  {
    title: 'Embedded Systems Internship',
    description: 'Completed an industry-focused internship in Embedded Systems covering microcontroller programming, hardware interfacing, communication protocols, and IoT development.',
    icon: '💼',
    color: '#E10600',
  },
  {
    title: 'VLSI Design Internship',
    description: 'Completed Maven Silicon VLSI Internship, working on real-world RTL design, simulation, verification, and digital hardware development.',
    icon: '🔬',
    color: '#E10600',
  },
  {
    title: 'Engineering Innovation',
    description: 'Designed and developed multiple engineering projects across RTL Design, FPGA, Embedded Systems, AIoT, Robotics, ESP32, PCB Design, and Hardware Prototyping.',
    icon: '🤖',
    color: '#E10600',
  },
  {
    title: 'Technical Content Creation',
    description: 'Prepared comprehensive technical documentation, tutorials, and engineering blogs covering IoT, embedded systems, and AIoT, contributing to developer learning.',
    icon: '📚',
    color: '#E10600',
  },
  {
    title: 'Professional Engineering Experience',
    description: 'Contributed to Embedded Systems, AIoT, Robotics, PCB Design, and RTL Design at Kiwistron Pvt Ltd — working on real-world engineering products.',
    icon: '🛠',
    color: '#E10600',
  },
] as const;

export const CONTACT_INFO = {
  email: 'varunssvk543@gmail.com',
  phone: '+91 9566622885',
  github: 'https://github.com/VarunPrasad07',
  linkedin: 'https://www.linkedin.com/in/varunprasad07/',
  location: 'Tamil Nadu, India',
  role: 'RTL Design Engineer | Embedded Systems Engineer | AIoT & Robotics Developer',
} as const;
